-- ============================================================
-- PASO 1: Columnas en newsletter_contactos
-- ============================================================
ALTER TABLE newsletter_contactos
  ADD COLUMN IF NOT EXISTS idioma text DEFAULT 'es',
  ADD COLUMN IF NOT EXISTS nombre text;

-- ============================================================
-- PASO 2: Tabla de campañas programadas
-- ============================================================
CREATE TABLE IF NOT EXISTS newsletter_campanas (
  id             uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  subject_eu     text,
  body_eu        text,
  subject_es     text,
  body_es        text,
  programado_para timestamptz NOT NULL,
  estado         text        DEFAULT 'programado', -- 'programado' | 'enviado' | 'cancelado'
  enviado_en     timestamptz,
  enviados_eu    int,
  enviados_es    int,
  created_at     timestamptz DEFAULT now()
);

-- ============================================================
-- PASO 3: Activos (175 contactos — excluidos: contacto@niala.es,
--          magoniala@outlook.com, sonar.esperada-3l@icloud.com,
--          calvolandam@icloud.com (baja), calvolandam@me.com)
-- Idioma: EUSKARA → eu · GAZTELERA → es · sin tag → es
-- ============================================================
INSERT INTO newsletter_contactos (email, nombre, idioma, origen, unsubscribed)
VALUES
  ('neretick8023@gmail.com',              'Carlos Freire',              'eu', 'importado', false),
  ('rafael.zulaika@museoa.eus',           'Rafael',                     'eu', 'importado', false),
  ('jnbilbao1966@gmail.com',              NULL,                         'es', 'importado', false),
  ('oierjm@gmail.com',                    NULL,                         'es', 'importado', false),
  ('aritzpetrikorena@gmail.com',          'Aritz',                      'es', 'importado', false),
  ('paguado@bancsabadell.com',            'Pilar',                      'es', 'importado', false),
  ('edurne@imh.eus',                      'Edurne',                     'eu', 'importado', false),
  ('imendezperez44@gmail.com',            NULL,                         'es', 'importado', false),
  ('lmoreno@galdakao.eus',                NULL,                         'eu', 'importado', false),
  ('rebeca_4@yahoo.com',                  'Rebeca',                     'es', 'importado', false),
  ('anelzurutuza@gmail.com',              'Ane',                        'eu', 'importado', false),
  ('110572@gmail.com',                    'Imanol',                     'eu', 'importado', false),
  ('apnjm@hotmail.es',                    NULL,                         'es', 'importado', false),
  ('ilopezsanchezgv@gmail.com',           NULL,                         'es', 'importado', false),
  ('jokinrm@yahoo.es',                    'Jokin',                      'es', 'importado', false),
  ('aznal_erik@eitb.eus',                 'Erik',                       'eu', 'importado', false),
  ('gorkarge@hotmail.com',                NULL,                         'es', 'importado', false),
  ('canadian4514@gmail.com',              NULL,                         'es', 'importado', false),
  ('oskar_zarautz@hotmail.com',           NULL,                         'es', 'importado', false),
  ('oierdisat@gmail.com',                 'Oier',                       'es', 'importado', false),
  ('ugarotarrak@gmail.com',               'Ugarotarrak',                'es', 'importado', false),
  ('agitzkontent@hotmail.com',            NULL,                         'es', 'importado', false),
  ('kultura@aduna.eus',                   'Dani',                       'eu', 'importado', false),
  ('naiara_gervasini@yahoo.es',           'Naiara',                     'es', 'importado', false),
  ('colomerbru@gmail.com',                NULL,                         'es', 'importado', false),
  ('kamude142000@gmail.com',              'Karlos',                     'es', 'importado', false),
  ('eruizdez@kutxabank.es',               'Endika',                     'es', 'importado', false),
  ('isabel.crespo1988@gmail.com',         'Isabel',                     'es', 'importado', false),
  ('aitzialava.aza@gmail.com',            'Aitziber',                   'eu', 'importado', false),
  ('alaitzsa@hotmail.com',                'Alaitz',                     'eu', 'importado', false),
  ('amaia.alonso@mendebaldea.net',        'Amaia',                      'eu', 'importado', false),
  ('recinov381@capiena.com',              'Raul Laskurain',             'eu', 'importado', false),
  ('arantza.brugat@monbake.com',          'Arantza',                    'es', 'importado', false),
  ('enaradominguezriguero@gmail.com',     'Enara',                      'eu', 'importado', false),
  ('itsafake8232@gmail.com',              NULL,                         'es', 'importado', false),
  ('amaiagarciadealbizu@gmail.com',       'Amaia',                      'eu', 'importado', false),
  ('aitormartinhernandez@gmail.com',      'Aitor',                      'es', 'importado', false),
  ('olabeunax@gmail.com',                 NULL,                         'es', 'importado', false),
  ('maizpi20@gmail.com',                  'Markel',                     'es', 'importado', false),
  ('aranmariii@gmail.com',                NULL,                         'es', 'importado', false),
  ('msesmamiguel@yahoo.com',              'Miguel',                     'es', 'importado', false),
  ('iturtriki@hotmail.com',               NULL,                         'eu', 'importado', false),
  ('gorkaacs@gmail.com',                  NULL,                         'es', 'importado', false),
  ('ielarranaga@elgoibarikastola.eus',    'Iera',                       'eu', 'importado', false),
  ('zancajoisabel@gmail.com',             'Isabel',                     'es', 'importado', false),
  ('animacion@gmail.com',                 'Nekane Elorduy',             'es', 'importado', false),
  ('bzubi8@gmail.com',                    NULL,                         'eu', 'importado', false),
  ('saioaalba@hotmail.com',               NULL,                         'es', 'importado', false),
  ('almilofer@gmail.com',                 NULL,                         'es', 'importado', false),
  ('iimazmunduate@gmail.com',             'Iñaki Imaz Munduate',        'eu', 'importado', false),
  ('ileon@somosexperiences.com',          'Ibai',                       'eu', 'importado', false),
  ('smanzanero@cbg.com.es',               'Santiago',                   'es', 'importado', false),
  ('alvaroilusionista@gmail.com',         'Alvaro',                     'eu', 'importado', false),
  ('dianabravogomez1980@icloud.com',      'Ama',                        'es', 'importado', false),
  ('maialenandres26@gmail.com',           'Maialen',                    'es', 'importado', false),
  ('ioritzyoyete@gmail.com',              NULL,                         'es', 'importado', false),
  ('ainarazal@hotmail.com',               'Ainara Zaldua',              'eu', 'importado', false),
  ('anton@mtemachine.com',                'Anton',                      'eu', 'importado', false),
  ('themagicdave1@gmail.com',             NULL,                         'es', 'importado', false),
  ('lekanazpi@gmail.com',                 'Lekanazpi kultur elkartea',  'eu', 'importado', false),
  ('maclipmagia@gmail.com',               'Eder de la Torre',           'eu', 'importado', false),
  ('eguzargi@gmail.com',                  NULL,                         'eu', 'importado', false),
  ('maiderlete@gmail.com',                'Maider',                     'eu', 'importado', false),
  ('martafcerrada@gmail.com',             'Marta Fernández Cerrada',    'es', 'importado', false),
  ('ancutaioanaberinde@gmail.com',        'Ancuta Ioana',               'es', 'importado', false),
  ('ezkportu@gmail.com',                  'Txema',                      'eu', 'importado', false),
  ('ane1.larrakoetxea@gmail.com',         'Ane',                        'es', 'importado', false),
  ('alvalofer@hotmail.com',               'Alva',                       'es', 'importado', false),
  ('carolina.figoli@americantower.com',   'Carolina Figoli',            'es', 'importado', false),
  ('malarranaga@hotmail.es',              'Marc Larrañaga Garcia',      'es', 'importado', false),
  ('oficinajavitxu@gmail.com',            'Javier',                     'es', 'importado', false),
  ('7iete.yeray@gmail.com',               NULL,                         'es', 'importado', false),
  ('jcarlos.mollet@hotmail.com',          NULL,                         'es', 'importado', false),
  ('rauljuarez@outlook.com',              NULL,                         'es', 'importado', false),
  ('iker_gd@hotmail.com',                 'Iker',                       'es', 'importado', false),
  ('jesus.beamonte@outlook.com',          'Jesus',                      'es', 'importado', false),
  ('sara.perez-martinez@sts-certified.com', 'Sara',                     'es', 'importado', false),
  ('carlos@magocarlosrubio.com',          'Carlos',                     'es', 'importado', false),
  ('anderaranzabal8@gmail.com',           'Ander',                      'eu', 'importado', false),
  ('johannmartingomez@gmail.com',         'Johan',                      'es', 'importado', false),
  ('mgomez@paradigmadigital.com',         'Marta',                      'es', 'importado', false),
  ('thereadinroom@gmail.com',             NULL,                         'es', 'importado', false),
  ('noramugerza23@gmail.com',             'Nora Muguerza',              'eu', 'importado', false),
  ('ardantzatolo@gmail.com',              NULL,                         'eu', 'importado', false),
  ('mlz-malu@hotmail.com',                NULL,                         'es', 'importado', false),
  ('mferreroc@hotmail.com',               NULL,                         'es', 'importado', false),
  ('zbernal@bergara.eus',                 NULL,                         'eu', 'importado', false),
  ('txissss@gmail.com',                   NULL,                         'es', 'importado', false),
  ('xiker_epelde@hotmail.com',            NULL,                         'es', 'importado', false),
  ('hachoner@gmail.com',                  NULL,                         'es', 'importado', false),
  ('arimambanegra@hotmail.com',           'Arianne',                    'es', 'importado', false),
  ('nuneskin10@gmail.com',                'Nuria',                      'es', 'importado', false),
  ('ovejas13@gmail.com',                  'Raquel',                     'es', 'importado', false),
  ('arevaloana@yahoo.es',                 'Ana',                        'es', 'importado', false),
  ('vanesaalainez@hotmail.com',           'Vanesa',                     'es', 'importado', false),
  ('buamagia@gmail.com',                  'Bran',                       'eu', 'importado', false),
  ('danielhuarte@yahoo.es',               'Daniel',                     'es', 'importado', false),
  ('unai.holgado@gruposarea.com',         'Unai',                       'es', 'importado', false),
  ('joelpablos.ed@gmail.com',             'Joel',                       'es', 'importado', false),
  ('maikicrespocbx@gmail.com',            'Maiki',                      'eu', 'importado', false),
  ('laumar-bi@hotmail.com',               NULL,                         'eu', 'importado', false),
  ('thomas.vialoiseau@gmail.com',         'Tommy',                      'es', 'importado', false),
  ('faktoria@eitb.eus',                   'EITB Faktoria',              'eu', 'importado', false),
  ('ampa.uribarrieskola@gmail.com',       'Nerea',                      'eu', 'importado', false),
  ('uzberistain@gmail.com',               'Unai',                       'eu', 'importado', false),
  ('davidvilaballus@gmail.com',           'David',                      'es', 'importado', false),
  ('pmarting93@gmail.com',                NULL,                         'es', 'importado', false),
  ('maosa@kirikino.com',                  'Maialen',                    'eu', 'importado', false),
  ('leticiaroquette@gmail.com',           'Leticia',                    'eu', 'importado', false),
  ('david.blanco0678@gmail.com',          NULL,                         'es', 'importado', false),
  ('amaiagomez46@gmail.com',              NULL,                         'es', 'importado', false),
  ('110572ima@gmail.com',                 'Imanol Gómez',               'eu', 'importado', false),
  ('mirarimz@yahoo.com',                  'Mirari',                     'es', 'importado', false),
  ('melixuca1986@hotmail.com',            NULL,                         'es', 'importado', false),
  ('amandatatoo@hotmail.com',             NULL,                         'es', 'importado', false),
  ('joseluisgava@hotmail.com',            NULL,                         'es', 'importado', false),
  ('juanelmago2009@gmail.com',            NULL,                         'es', 'importado', false),
  ('jone.karkamo@gmail.com',              NULL,                         'es', 'importado', false),
  ('geur79@gmail.com',                    'Geaxi',                      'eu', 'importado', false),
  ('suvillos2014@gmail.com',              NULL,                         'es', 'importado', false),
  ('jsellares@hotmail.com',               'Jorge',                      'eu', 'importado', false),
  ('alberto@aygcomunicacion.com',         'Alberto',                    'es', 'importado', false),
  ('miriamsastre@hotmail.com',            'Miriam Sastre',              'es', 'importado', false),
  ('joan-riu@hotmail.com',                NULL,                         'es', 'importado', false),
  ('jorgearan@gmail.com',                 'Jorge',                      'eu', 'importado', false),
  ('mariancv@msn.com',                    'Marian Castellanos',         'es', 'importado', false),
  ('sasiburu@gmail.com',                  'Felipe Quintanilla',         'eu', 'importado', false),
  ('elcorreodetxus@yahoo.es',             'Txus',                       'es', 'importado', false),
  ('uxuerios26@gmail.com',                'Uxue',                       'eu', 'importado', false),
  ('mji67@hotmail.es',                    NULL,                         'es', 'importado', false),
  ('kultura@asteasu.eus',                 'Axier',                      'eu', 'importado', false),
  ('iagoazkue@gmail.com',                 'Iago',                       'eu', 'importado', false),
  ('jirizar44@gmail.com',                 NULL,                         'eu', 'importado', false),
  ('hugo2323diez@gmail.com',              'Hugo',                       'eu', 'importado', false),
  ('josuburga@gmail.com',                 NULL,                         'es', 'importado', false),
  ('imanolcerdeira@gmail.com',            'Imanol',                     'eu', 'importado', false),
  ('olatzfuente@hotmail.com',             'Olatz',                      'eu', 'importado', false),
  ('oeguren31@gmail.com',                 'Oier',                       'eu', 'importado', false),
  ('txeppas@gmail.com',                   'Eduardo',                    'es', 'importado', false),
  ('alvarogrot@gmail.com',                'Álvaro',                     'es', 'importado', false),
  ('merakimakur@gmail.com',               'David',                      'eu', 'importado', false),
  ('aioramendiburu@gmail.com',            'Aiora',                      'eu', 'importado', false),
  ('sonlascincodelatarde@gmail.com',      NULL,                         'es', 'importado', false),
  ('mcjanez@hotmail.com',                 'Mari Carmen',                'es', 'importado', false),
  ('jonenkontuak@gmail.com',              NULL,                         'eu', 'importado', false),
  ('kultura@berrobi.eus',                 'Iker',                       'eu', 'importado', false),
  ('liburutegia@elgoibar.eus',            NULL,                         'eu', 'importado', false),
  ('dougjkelly@hotmail.com',              NULL,                         'es', 'importado', false),
  ('jorgiaran@gmail.com',                 'Jorge',                      'eu', 'importado', false),
  ('saradelvallee16@gmail.com',           'Sara',                       'eu', 'importado', false),
  ('tammy.alho81@gmail.com',              NULL,                         'es', 'importado', false),
  ('euwwriter@gmail.com',                 NULL,                         'es', 'importado', false),
  ('dianae40@hotmail.com',                NULL,                         'es', 'importado', false),
  ('alodismagic@gmail.com',               'Alodis',                     'es', 'importado', false),
  ('adrymc72@hotmail.com',                NULL,                         'es', 'importado', false),
  ('asier.saizar.diaz@gmail.com',         NULL,                         'es', 'importado', false),
  ('nerea_orive@hotmail.com',             'Mara',                       'eu', 'importado', false),
  ('oscaroncala@hotmail.com',             NULL,                         'es', 'importado', false),
  ('administracion@colegiotrueba.net',    'Txema Ansuategui Arias',     'es', 'importado', false),
  ('sergiommagia@gmail.com',              'Sergio',                     'eu', 'importado', false),
  ('edurne.alava.urbina@gmail.com',       'Edurne',                     'eu', 'importado', false),
  ('farinasvictor7@gmail.com',            'Victor',                     'es', 'importado', false),
  ('jonoregi@gmail.com',                  NULL,                         'es', 'importado', false),
  ('lmpgus4@hotmail.com',                 NULL,                         'es', 'importado', false),
  ('yhernandez@cmgipuzkoa.com',           'Yaiza',                      'es', 'importado', false),
  ('javiirow214@gmail.com',               'Javi',                       'es', 'importado', false),
  ('admin.leaibarra@bizkaia.org',         'Lea Ibarra Amankomunazgoa',  'eu', 'importado', false),
  ('onehdi@gmail.com',                    NULL,                         'eu', 'importado', false),
  ('josuneblanco@hotmail.com',            NULL,                         'es', 'importado', false),
  ('aitoriglesiass1@gmail.com',           'Aitor',                      'eu', 'importado', false),
  ('pkgarzia@gmail.com',                  NULL,                         'eu', 'importado', false),
  ('nagore_moreno@yahoo.es',              NULL,                         'es', 'importado', false),
  ('sandraja@gmail.com',                  'Sandra',                     'eu', 'importado', false),
  ('magomarlocarambola@gmail.com',        NULL,                         'es', 'importado', false),
  ('beatriz.fraile@stratesys-ts.com',     'Beatriz',                    'es', 'importado', false)
ON CONFLICT (email) DO NOTHING;

-- ============================================================
-- PASO 4: Desuscritos (127 contactos — CSV unsubscribed_2bb3d83b86)
-- Nota: DO UPDATE garantiza que si alguien está en ambas listas,
-- "desuscrito" gana (ej: curcobein99@gmail.com aparece en los dos).
-- ============================================================
INSERT INTO newsletter_contactos (email, nombre, idioma, origen, unsubscribed)
VALUES
  ('mariotorres808@gmail.com',             'Mario',                     'es', 'importado', true),
  ('iranzoaitor@gmail.com',                'Aitor',                     'es', 'importado', true),
  ('blacker08@gmail.com',                  'Cristina',                  'es', 'importado', true),
  ('upagoaga@gmail.com',                   NULL,                        'es', 'importado', true),
  ('berrikuntza@sangabrieleskola.net',     'Patxi',                     'eu', 'importado', true),
  ('juanjolabaien@gmail.com',              'Juanjo',                    'es', 'importado', true),
  ('sony.higuera@gmail.com',               NULL,                        'es', 'importado', true),
  ('olatzba@hotmail.com',                  NULL,                        'eu', 'importado', true),
  ('herrielkarlana@gmail.com',             'Maider',                    'eu', 'importado', true),
  ('olakauzoelkartea@gmail.com',           NULL,                        'eu', 'importado', true),
  ('gonzalomateosmagia@gmail.com',         NULL,                        'es', 'importado', true),
  ('ipuentesalgado@gmail.com',             NULL,                        'es', 'importado', true),
  ('gonmagon@icloud.com',                  NULL,                        'es', 'importado', true),
  ('leizeerretegia@gmail.com',             'ROKY',                      'eu', 'importado', true),
  ('komunikazioa@debegesa.eus',            'Maria',                     'es', 'importado', true),
  ('m.vidal.dlc@gmail.com',               'María Vidal',               'es', 'importado', true),
  ('etxenagusiana@gmail.com',              NULL,                        'eu', 'importado', true),
  ('tyrone@c-languages.com',               'Tyrone',                    'eu', 'importado', true),
  ('14iaba@jakintzaikastola.eus',          'Ian',                       'eu', 'importado', true),
  ('inalleja@gmail.com',                   NULL,                        'es', 'importado', true),
  ('julentoral2005@gmail.com',             NULL,                        'es', 'importado', true),
  ('laura.sc83@gmail.com',                 NULL,                        'es', 'importado', true),
  ('noemi_986@hotmail.com',                'Noemi',                     'es', 'importado', true),
  ('ivanortesp@gmail.com',                'Ivan',                       'es', 'importado', true),
  ('animacion@bilbao.eus',                 'Maria',                     'es', 'importado', true),
  ('vap1000@hotmail.es',                   NULL,                        'es', 'importado', true),
  ('maitotxas@gmail.com',                  'Maite',                     'es', 'importado', true),
  ('eneritzpagalday@yahoo.es',             NULL,                        'es', 'importado', true),
  ('alvarolopezilusionista@gmail.com',     'Alvaro',                    'es', 'importado', true),
  ('adrymcr78@gmail.com',                  NULL,                        'es', 'importado', true),
  ('tomas.labarga@movistar.es',            'Tomas',                     'es', 'importado', true),
  ('helenamorenita@gmail.com',             NULL,                        'es', 'importado', true),
  ('talfonva@gmail.com',                   NULL,                        'es', 'importado', true),
  ('saragarria46@gmail.com',               'Sara',                      'es', 'importado', true),
  ('isabelisabelcueva@gmail.com',          NULL,                        'es', 'importado', true),
  ('lourdes.fernandez.gonzales@gmail.com', 'Lourdes',                   'es', 'importado', true),
  ('012768aa@hezkuntza.net',               NULL,                        'eu', 'importado', true),
  ('otazpi2@gmail.com',                    'Xabi',                      'eu', 'importado', true),
  ('psagarna@cieautomotive.com',           'Patricia',                  'es', 'importado', true),
  ('i-aizpuruaiturralde@euskadi.eus',      'Idurre Aizpurua',           'eu', 'importado', true),
  ('vanesa_ermua@yahoo.es',                NULL,                        'es', 'importado', true),
  ('info@rubiferez.com',                   'Rubi',                      'es', 'importado', true),
  ('julenetxu@hotmail.com',                'Julene',                    'eu', 'importado', true),
  ('julenurtxegi@gmail.com',               'Julen',                     'eu', 'importado', true),
  ('ikasi@ingeniariak.eus',                'Saioa',                     'es', 'importado', true),
  ('otamendi46@hotmail.com',               NULL,                        'es', 'importado', true),
  ('ibaizangi@gmail.com',                  'Ibai',                      'es', 'importado', true),
  ('ajuria_amaia@outlook.es',              'Amaia',                     'eu', 'importado', true),
  ('luis.barreiro@ayesa.com',              'Luis',                      'es', 'importado', true),
  ('carlosalarconabeso@gmail.com',         NULL,                        'es', 'importado', true),
  ('juanjosezerpa@hotmail.com',            'Juanjose',                  'eu', 'importado', true),
  ('aisia@geuelkartea.eus',                'Geu Elkartea',              'eu', 'importado', true),
  ('nereagaralde@yahoo.es',                'Nerea',                     'es', 'importado', true),
  ('gabrielcad2004gc@gmail.com',           'Leonardo Gabriel',          'es', 'importado', true),
  ('castelruiz@gmail.com',                 NULL,                        'es', 'importado', true),
  ('edwin.kadar@gmail.com',                'Edwin',                     'es', 'importado', true),
  ('ainara_lazkano@hotmail.com',           'Ainara Lazkano',            'eu', 'importado', true),
  ('a.aldabaldetreku@hotmail.com',         'Alaitz',                    'es', 'importado', true),
  ('jmendizabal@taupamugimendua.eus',      NULL,                        'eu', 'importado', true),
  ('alaznezubi@gmail.com',                 'Alazne',                    'eu', 'importado', true),
  ('euskera@condadodetrevino.es',          'Euskara Teknikaria',        'es', 'importado', true),
  ('ibai.intxaurrondo@gmail.com',          NULL,                        'eu', 'importado', true),
  ('anemirenmoreno@gmail.com',             NULL,                        'es', 'importado', true),
  ('salberdi@meka.eus',                    'Saioa',                     'eu', 'importado', true),
  ('pilarmpadilla33@gmail.com',            'Pilar',                     'eu', 'importado', true),
  ('davidmdorlet@gmail.com',               NULL,                        'es', 'importado', true),
  ('paula.febrero@portdebarcelona.cat',    NULL,                        'es', 'importado', true),
  ('ricardo@exclusivasgorla.es',           NULL,                        'es', 'importado', true),
  ('jone.carballeda@outlook.com',          NULL,                        'eu', 'importado', true),
  ('gespe777@gmail.com',                   NULL,                        'es', 'importado', true),
  ('izaskuun@gmail.com',                   NULL,                        'eu', 'importado', true),
  ('ardegauna1972@gmail.com',              NULL,                        'es', 'importado', true),
  ('idurrele@gmail.com',                   NULL,                        'es', 'importado', true),
  ('zurinezarate@lekeitiobhi.net',         'Zurine Zarate Alonso',      'es', 'importado', true),
  ('aimarcoida@gmail.com',                 NULL,                        'es', 'importado', true),
  ('usoaegurbide@gmail.com',               'Usoa',                      'eu', 'importado', true),
  ('sanclementet@gmail.com',               'Tatiana',                   'es', 'importado', true),
  ('garciamartinezblanca@gmail.com',       'Blanka Garcia',             'eu', 'importado', true),
  ('nahikari.barrio@antzuolahlhi.eus',     'Nahikari',                  'eu', 'importado', true),
  ('inigofeijoo98@gmail.com',              NULL,                        'es', 'importado', true),
  ('ameliarhn2004@gmail.com',              NULL,                        'es', 'importado', true),
  ('illafruela@gmail.com',                 NULL,                        'es', 'importado', true),
  ('pablomartarias@gmail.com',             'Pablo',                     'eu', 'importado', true),
  ('jofexbar@gmail.com',                   NULL,                        'es', 'importado', true),
  ('teresaalonsomajagranzas@gmail.com',    'Teresa',                    'es', 'importado', true),
  ('lucia@vidext.io',                      'Lucia',                     'es', 'importado', true),
  ('maegues@gmail.com',                    NULL,                        'es', 'importado', true),
  ('manaya@mondragon.edu',                 'Maite',                     'es', 'importado', true),
  ('julio@magiaycardistry.com',            NULL,                        'es', 'importado', true),
  ('ucp600icc@gmail.com',                  'Amaia',                     'es', 'importado', true),
  ('peiorivas03@gmail.com',                'Peio Rivas',                'es', 'importado', true),
  ('maialentorrehigon@gmail.com',          'Maialen',                   'es', 'importado', true),
  ('leireegana1@gmail.com',                'Leire',                     'es', 'importado', true),
  ('asierpresa@hotmail.com',               NULL,                        'es', 'importado', true),
  ('centocarbo@gmail.com',                 'Cento',                     'es', 'importado', true),
  ('ingeheobarakaldo@gmail.com',           NULL,                        'eu', 'importado', true),
  ('caizpurua@landaberrikastola.org',      'Consuelo Aizpurua',         'eu', 'importado', true),
  ('xabierbernar@gmail.com',               'Xabier',                    'eu', 'importado', true),
  ('irairaitz@gmail.com',                  NULL,                        'es', 'importado', true),
  ('mirearesan17@gmail.com',               'Miren',                     'es', 'importado', true),
  ('ludotekaelgoibar@gmail.com',           'Elgoibarko ludoteka',       'eu', 'importado', true),
  ('rubengarciasilva@hotmail.com',         'Ruben',                     'es', 'importado', true),
  ('l.rodriguez.eguiguren@kzgunea.net',    'Leire',                     'es', 'importado', true),
  ('dasnenas@gmail.com',                   NULL,                        'es', 'importado', true),
  ('oderrsaid2@gmail.com',                 NULL,                        'es', 'importado', true),
  ('jordi.rotllan@lcibarcelona.com',       NULL,                        'es', 'importado', true),
  ('igibaim1@gmail.com',                   NULL,                        'es', 'importado', true),
  ('urkoazpiga@gmail.com',                 'Urko',                      'es', 'importado', true),
  ('hugojala@gmail.com',                   'Hugo',                      'es', 'importado', true),
  ('ismeneita@hotmail.com',                NULL,                        'es', 'importado', true),
  ('invictusstinger@gmail.com',            'Dogma',                     'es', 'importado', true),
  ('alara@alara.eus',                      'Maite',                     'es', 'importado', true),
  ('libelaia@outlook.com',                 NULL,                        'es', 'importado', true),
  ('zuzendaria@sanluislasalle.eus',        NULL,                        'eu', 'importado', true),
  ('aiaratekak@gmail.com',                 'Aiarateka',                 'es', 'importado', true),
  ('magdalena.izaguirre@deusto.es',        'Magdalena',                 'es', 'importado', true),
  ('maitanecarrasco@gmail.com',            NULL,                        'es', 'importado', true),
  ('aotaola@virtualwareco.com',            'Aida',                      'es', 'importado', true),
  ('robertogaston.gervasini@gmail.com',    NULL,                        'es', 'importado', true),
  ('andrespinagarcia@gmail.com',           'Andrés',                    'es', 'importado', true),
  ('curcobein99@gmail.com',               'Jon Gomez Sanz',             'eu', 'importado', true),
  ('maria.arandiaa@gmail.com',             'Maria',                     'es', 'importado', true),
  ('designsdante@gmail.com',               'Dante',                     'eu', 'importado', true),
  ('mikcorcas@gmail.com',                  'Mikel',                     'es', 'importado', true),
  ('iagorria@topagunea.eus',               NULL,                        'es', 'importado', true),
  ('nessa2221@gmail.com',                  NULL,                        'es', 'importado', true),
  ('otaegui.ainhoa@gmail.com',             NULL,                        'es', 'importado', true)
ON CONFLICT (email) DO UPDATE SET unsubscribed = true;
